### ISSUE TITLE
wavesurfer.js with Ionic/Cordova

### ISSUE THREAD

**Issue by JensWinter** [wavesurfer-js/wavesurfer.js#761]
Hello there,

can someone point me to some sample with a successfully implemented wavesurfer.js inside of an Ionic/Cordova project?

I can't get it to work. The Wave control does not show up. I can hook up a play button and play the audio, though. But I seem to be missing something.

Any help is greatly appreciated!

Thanks in advance,
Jens

**Comment by pentool** [comment]
We are experiencing the same issue. Rending the waveform is nearly impossible. And yes, the audio does play, but doesn't really look pretty without the waveform, though.

**Comment by entonbiba** [comment]
@JensWinter is it ionic 1 or 2 and do any errors come up in console?

**Comment by JensWinter** [comment]
@entonbiba It's Ionic 1.

**Comment by entonbiba** [comment]
@JensWinter do you have the code that you are using? I'm using the latest versions for ionic 1, angular and wavesurfer. Just tested the following below and it renders correctly. 

in www/index.html add within <ion-content></ion-content>:
```
      <div id="waveform"></div>

      <button class="btn btn-primary" ng-click="play()">
        <i class="glyphicon glyphicon-play"></i>
        Play
      </button>
```


in www/js/app.js add:
```
  angular.module('ionicApp', ['ionic']).controller('MyCtrl', function ($scope) {
      var wavesurfer = WaveSurfer.create({
          container: '#waveform',
          waveColor: 'red',
          progressColor: 'purple'
      });
      wavesurfer.load('https://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3');
      $scope.play = function () {
          wavesurfer.play();
      };
  });
```

**Comment by pentool** [comment]
I'm guessing it's Cordova and not ionic or angular. We are using it with React/Cordova app and it doesn't work in react either neither on iOS nor on Android. Only the audio. But no waveform. In a browser, yes. It does work. But as soon as you use it in a mobile project (like with cordova) it doesn't.

**Comment by andrewex** [comment]
Any luck getting this to work with Ionic 3?

**Comment by lukewduncan** [comment]
Anyone have any luck? I have it working in the browser but no mobile

**Comment by Graghav** [comment]
![img_1516_1024](https://user-images.githubusercontent.com/5223649/27262330-13bd6916-5472-11e7-80eb-850e4646595e.jpg)
@lukewduncan I was able to use Wavesurfer successfully with Cordova 7.0.1.

`<div class="audio_card card">
        <div id="waveform" class="waveform"></div>
  </div>`

In Controller,
`var wavesurfer = WaveSurfer.create({
					container: '#waveform',
					waveColor: 'white',
					progressColor: '#5600ed',
					cursorColor: 'transparent',
					barWidth : 2.5,
					height 	 : 100
				});

   wavesurfer.load(file);
   wavesurfer.on('ready', function () {				
        wavesurfer.play();
   });
`

**Comment by lukewduncan** [comment]
@Graghav have you done anything special to the div your attaching Wavesurfer too? (maybe specific css or using something other than a div).

It's so weird that I can see it on the browser (chrome) but when I run the application on a device, no show. But thanks for providing the example, I'll just copy the exact Wavesurfer class you have and load everything that way.

**Comment by Graghav** [comment]
@lukewduncan I have made the waveform element as absolute with the parent card being relative and gave a z-index of 100 to the waveform element,

```
.waveform {
       height: 50%;
       width: 100%;
       padding-left: 15px;
       padding-right: 15px;
       position: absolute;
       z-index: 100;
}
```

**Comment by lukewduncan** [comment]
@Graghav have you tried on android, or only on iOS?

**Comment by Graghav** [comment]
@lukewduncan I am using it on iOS. Let me try on Android and update you.

**Comment by Graghav** [comment]
@lukewduncan Tried on Android and it works fine

![screenshot_2017-06-20-14-20-15-279_1024](https://user-images.githubusercontent.com/5223649/27324789-e18928e2-55c3-11e7-95a9-3fc8895df320.jpg)

**Comment by Darkensses** [comment]
Thanks to @Graghav for show us that is possible and he has reason. I had error: 'Container element not found' beacuse I had a 'global variable' but it was fixed it when i wrote my code inside a method. If sombody can explain me why or which is the difference I will appreciate it :) :+1: 

Correct:
![correct](https://user-images.githubusercontent.com/23271049/28148985-d7327aa4-674f-11e7-84a5-968644758fbf.PNG)

Doesn't work:
![wrong](https://user-images.githubusercontent.com/23271049/28148986-d73c74aa-674f-11e7-9288-f37cb92a757a.PNG)

**Comment by Darkensses** [comment]
@lukewduncan have you try to add permissons? if you are trying with the example you need to add 'whitelist plugin' because you are accessing to mp3 file from a http request. If your are loading file from local storage you need to add other plugins also, like 'cordova-plugin-file'. I'm not tesiting my app yet so i hope my answer be helpful.

https://github.com/apache/cordova-plugin-whitelist
https://github.com/apache/cordova-plugin-file/blob/master/doc/es/index.md

**Comment by shaktis110** [comment]
hey @Graghav  its not working in ionic 4 it still show the white screen

**Comment by FabianoB2ML** [comment]
@Graghav how are you? Fine? I hope so.

Well i'm trying to use your example in my application to but i have the same issue as @shaktis110. In ionic 5 show the white screen when a start my app.

Ionic version: 5.4.13
Cordova version 9.0.1

My HomePage.TS
![image](https://user-images.githubusercontent.com/45759701/71844502-0b90d680-30a5-11ea-9814-ad15d009a802.png)

My HomePage.html
![image](https://user-images.githubusercontent.com/45759701/71844553-2bc09580-30a5-11ea-8082-482b10b9fdbd.png)

My HomePage.scss
![image](https://user-images.githubusercontent.com/45759701/71844606-41ce5600-30a5-11ea-94d1-4f03c05fce71.png)

My App (white screen)
![image](https://user-images.githubusercontent.com/45759701/71844681-70e4c780-30a5-11ea-9155-05a6d7899f45.png)

Well, if any could help! Thanks :D

**Comment by kenjoegolo** [comment]
Have you guys made it working on ionic 5? I also having a problem - the audio and play/pause button is working but the waveform is not showing up.

I'm using ionic-react + capacitor

**Comment by entonbiba** [comment]
@kenjoegolo any errors in console?

**Comment by entonbiba** [comment]
can you try this sample code with your ionic app and use the latest version 4.4.0 please.
https://www.entonbiba.com/lab/ios2.html
